# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               IEEE@IIT
tagline:             'Illinois Tech IEEE Student Branch'
description:         "IEEE@IIT is Illinois Tech's branch of the Institute of Electrical and Electronics Engineers (IEEE). Read the <a href='{{ site.baseurl }}/about/'>About Us page</a> to learn more."
url:                 http://ieee.iit.io
baseurl:             
paginate:            5

# About/contact
author:
  name:              IEEE IIT
  url:               http://ieee.iit.edu/
  email:             ieee@iit.edu

# Custom vars
version:             1.0.0

ftp_host: 'myftp.iit.edu'
ftp_dir: '/www'
ftp_passive: false
ftp_username: 'ieee'
